name: Find and Replace v2
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: flcdrg/replace-multiple-action@v1
      with:
        files: './*xml'
        find: '[{ "find": "  ", "replace": "  "},{ "find": "fromJSON(\"/>)", "replace": "\" />"}]
