name: Find and Replace
on:
  # NOTE: Need to run on a PR so that the ${{ github.head_ref }} (branch) is non-null
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  fmt-code:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v3
=======
      - uses: actions/checkout@v4
>>>>>>> 4e06f3a7870b2a7801e4547bbb5e6dfd4df6d9af

      # Run steps that make changes to the local repo here.
      - name: Tabs to spaces
        run: find ./ -type f -name *.xml -exec sed -i -e 's/\t/  /g' -e 's/\"\/>/\" \/>/g' {} \;
        
      # Commit all changed files back to the repository
<<<<<<< HEAD
      - uses: planetscale/ghcommit-action@v0.1.6
=======
      - uses: planetscale/ghcommit-action@v0.1.13
>>>>>>> 4e06f3a7870b2a7801e4547bbb5e6dfd4df6d9af
        with:
          commit_message: "GitHub Action: Find and Replace"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
        env:
<<<<<<< HEAD
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
=======
          GITHUB_TOKEN: ${{secrets.FindAndReplacePAT}} #uses PAT rather than GITHUB_TOKEN due to not running actions once merged https://github.com/orgs/community/discussions/25702
>>>>>>> 4e06f3a7870b2a7801e4547bbb5e6dfd4df6d9af
